# Package Tests

This notebook will make some tests to check if the package is working correctly. We will start by doing some simple TOML files to check if the package is able to read them correctly. Then we will move on to more complex tests.

To initialize any object in the package, you will need to create a TOML file with the configuration of the object you want to create. The package will read this file and create the object accordingly.

In [2]:
from src.core import runner as pyrsnc

runner_obj = pyrsnc.Runner(config_path="test.toml")

At the initialization of the Runner object, the package will read the TOML file and create the object accordingly. If the TOML file is not found or is not valid, the package will raise an error. Let's start with a simple TOML file to check if the package is able to read it correctly. The TOML file will contain the configuration of a simple object that we will create.

Any TOML file must have at least the following info:
- A database provided
- A query to be executed on the database

```toml
[[database]]
name       = "sc6"
env_file   = ".env"  # It requires the .env file at the same path as the TOML file, otherwise specify the full path to the .env file
env_prefix = "SERVER_SC6"

[[queries]]
name       = "sc6"
sql_file   = "./queries/revision.sql"
description= "Query to retrieve events from SeisComP6 database"
database   = "sc6"
```

In [3]:
print(runner_obj.list_queries())

['SeisComP3', 'SeisComP6']

In [4]:
result = runner_obj.run()

In [5]:
result.total_events

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,quality_associatedStationCount,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment
0,2026-01-03 12:50:36+00:00,SGC2026aeqzwf,139.960938,4.138011,1.317026,3.805547,2.401441,2.632750,197.0,176.0,...,NaN,earthquake,SGC,"Villanueva - Santander, Colombia",6.714409,-73.151004,MLr_3,NonLinLoc,Poveda_et_al_2018,b'DESTACADO'
1,2026-01-03 18:02:57+00:00,SGC2026afbizi,37.070312,2.927446,1.382402,6.336486,3.090210,3.722662,72.0,59.0,...,NaN,earthquake,SGC,"Riosucio - ChocÃ³, Colombia",7.260504,-76.876872,MLr_1,NonLinLoc,Poveda_et_al_2018,None
2,2026-01-03 18:57:35+00:00,SGC2026afdebv,23.400000,0.856006,0.670000,8.500000,5.656854,5.656854,11.0,11.0,...,NaN,earthquake,SGC,"PulÃ­ - Cundinamarca, Colombia",4.723500,-74.642167,MLr_2,Hypo71,RSNC,None
3,2026-01-03 21:22:20+00:00,SGC2026afhyui,60.550000,1.535298,0.140000,12.500000,3.818377,3.818377,7.0,7.0,...,NaN,not locatable,SGC,"Puerto Wilches - Santander, Colombia",7.470667,-73.859833,MLr_vmm,Hypo71,RSNC,None
4,2026-01-03 22:22:32+00:00,SGC2026afjytm,139.492188,2.878409,1.290398,4.320529,2.712027,3.283069,122.0,111.0,...,NaN,earthquake,SGC,"Los Santos - Santander, Colombia",6.782142,-73.168157,MLr_3,NonLinLoc,Poveda_et_al_2018,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2559,2026-04-01 11:33:34+00:00,SGC2026gkcixf,53.796317,2.301955,0.620182,4.148976,3.168776,2.831864,24.0,24.0,...,NaN,earthquake,SGC,"Ciudad Bolívar - Antioquia, Colombia",5.814218,-75.944334,MLr_1,NonLinLoc,Poveda_et_al_2018,None
2560,2026-04-01 11:45:33+00:00,SGC2026gkctfd,10.000000,0.324661,4.036632,NaN,NaN,NaN,NaN,NaN,...,NaN,not locatable,SGC,"Dabeiba - Antioquia, Colombia",7.018000,-76.210000,MLr_1,,,None
2561,2026-04-01 11:51:58+00:00,SGC2026gkcysx,10.000000,1.144346,12.148123,NaN,NaN,NaN,NaN,NaN,...,NaN,not locatable,SGC,"San Gil - Santander, Colombia",6.592000,-73.182000,MLr_3,,,None
2562,2026-04-01 11:53:44+00:00,SGC2026gkdagl,130.612723,1.935232,0.633822,9.200862,5.277715,8.421233,19.0,19.0,...,NaN,earthquake,SGC,"Los Santos - Santander, Colombia",6.828385,-73.145575,MLr_3,NonLinLoc,Poveda_et_al_2018,None
2563,2026-04-01 11:55:42+00:00,SGC2026gkdbyo,10.000000,-0.779102,8.574671,NaN,NaN,NaN,NaN,NaN,...,NaN,not locatable,SGC,"La Esperanza - Norte de Santander, Colombia",7.705400,-73.334400,MLr_vmm,,,None

In [18]:
result.duplicates

Empty DataFrame
Columns: [time_value, publicID, depth_value, magnitude_value, quality_standardError, depth_uncertainty, latitude_uncertainty, longitude_uncertainty, quality_associatedPhaseCount, quality_usedPhaseCount, creationInfo_author, quality_usedStationCount, quality_associatedStationCount, event_type, creationInfo_agencyID, text, latitude_value, longitude_value, magnitude_type, methodID, earthModelID, comment]
Index: []

[0 rows x 22 columns]

In [19]:
result.checks

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
4890,2026-08-31 15:00:28+00:00,SGC2026rdjoym,4.510000,2.565373,0.400000,2.700000,1.484924,1.484924,18.0,18.0,...,earthquake,SGC,"Panamá - Colombia , Región Fronteriza",7.527167,-77.988167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
5086,2026-09-06 01:45:00+00:00,SGC2026rnjotn,95.496652,1.667690,0.376446,8.438027,7.487553,5.034114,14.0,14.0,...,earthquake,SGC,"La Victoria - Valle del Cauca, Colombia",4.476449,-76.082018,MLr_1,NonLinLoc,Poveda_et_al_2018,None,Incorrect magnitude type for zone1; Incorrect ...

In [7]:
result.output

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
0,2026-03-10 05:01:27+00:00,SGC2026evfjqe,115.020000,1.659107,0.380000,5.600000,3.889087,3.889087,14.0,14.0,...,earthquake,SGC,"Onzaga - Santander, Colombia",6.221167,-72.782667,MLr_3,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026evfjyn
1,2026-03-10 05:01:29+00:00,SGC2026evfjyn,144.580000,1.735847,0.310000,3.700000,5.232590,5.232590,11.0,11.0,...,earthquake,SGC,"San Vicente de ChucurÃ­ - Santander, Colombia",6.739833,-73.395000,MLr_vmm,Hypo71,VMM,None,SSWA: Possible duplicate event of SGC2026evfjqe
2,2026-03-18 15:22:57+00:00,SGC2026fkrugu,41.310000,2.821528,1.150000,0.000000,5.091169,5.091169,19.0,19.0,...,earthquake,SGC,Océano Pacífico,2.555333,-79.800333,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
3,2026-03-23 22:19:19+00:00,USGS_us7000s76i,14.520000,4.600000,0.720000,NaN,0.039300,0.061900,NaN,57.0,...,outside of network interest,USGS,"Puerto, Chile",-20.032900,-70.950000,mwr,,,,Event with comment different from DESTACADO
4,2026-03-26 22:53:32+00:00,SGC2026fzynny,1.000000,1.740561,0.370000,0.900000,0.707107,0.707107,14.0,14.0,...,earthquake,SGC,Colombia-Ecuador Border Region,0.793667,-77.929500,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
5,2026-05-07 17:29:00+00:00,SGC2026iyqgvw,0.010000,2.094457,0.480000,6.700000,3.323402,3.323402,7.0,7.0,...,explosion,SGC,"La Jagua de Ibirico - Cesar, Colombia",9.643167,-73.413000,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgwu
6,2026-05-07 17:29:02+00:00,SGC2026iyqgwu,20.350000,2.232984,1.000000,6.500000,5.303301,5.303301,15.0,13.0,...,explosion,SGC,"Becerrill - Cesar, Colombia",9.684000,-73.341333,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgvw
7,2026-05-08 23:06:59+00:00,SGC2026jaxezo,144.820871,2.195770,1.015575,6.296250,3.534268,4.819145,49.0,45.0,...,earthquake,SGC,"Los Santos - Santander, Colombia",6.791371,-73.110256,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxfag
8,2026-05-08 23:07:02+00:00,SGC2026jaxfag,168.039062,2.139073,0.912856,10.159535,10.171115,7.821433,19.0,19.0,...,earthquake,SGC,"Arboledas - Norte de Santander, Colombia",7.534811,-72.944324,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxezo
9,2026-05-30 21:27:25+00:00,USGS2026gcdsqo,35.000000,5.600000,NaN,NaN,NaN,NaN,NaN,NaN,...,outside of network interest,USGS,"Oistins, Barbados",11.900000,-59.100000,mb,,,None,SSWA: Possible duplicate event of SGC2026kpdwsu
10,2026-05-30 21:27:28+00:00,SGC2026kpdwsu,32.385475,5.519399,1.484747,6.384253,2.480362,5.504258,140.0,125.0,...,outside of network interest,SGC,Windward Islands,12.124347,-59.531719,Mw(Mwp),LOCSAT,iasp91,None,SSWA: Possible duplicate event of USGS2026gcdsqo
11,2026-06-18 09:27:40+00:00,SGC2026lxcvaw,20.000000,2.326374,1.240000,6.200000,2.899138,2.899138,22.0,20.0,...,earthquake,SGC,Océano Pacífico,5.852167,-78.327667,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
12,2026-08-11 08:12:57+00:00,SGC2026psdoen,42.390000,1.452818,0.330000,9.600000,1.909188,1.909188,18.0,10.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.144667,-76.788333,MLr_1,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026psdocc
13,2026-08-11 08:13:00+00:00,SGC2026psdocc,54.027344,2.750620,1.297853,6.703477,3.231052,3.083073,72.0,71.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.120063,-76.769755,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026psdoen
14,2026-08-11 09:03:38+00:00,SGC2026psffvr,4.320000,3.135464,1.170000,3.100000,2.333452,2.333452,69.0,68.0,...,earthquake,SGC,Océano Pacífico,3.054667,-79.252167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
15,2026-08-14 13:08:08+00:00,SGC2026pyanec,45.248326,3.238456,1.061230,5.151300,2.164437,2.468013,120.0,117.0,...,earthquake,SGC,"Istmina - Chocó, Colombia",4.464816,-76.705386,MLr_1,NonLinLoc,Poveda_et_al_2018,DESTACADO\n,Event with comment different from DESTACADO
16,2026-08-24 05:34:33+00:00,SGC2026qputsi,88.796875,1.965782,0.842429,7.729107,5.951305,9.399577,27.0,24.0,...,earthquake,SGC,"Sipí - Chocó, Colombia",4.698529,-76.328161,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputel
17,2026-08-24 05:34:35+00:00,SGC2026qputel,101.503348,1.668413,0.742718,7.017535,4.969709,9.876757,23.0,23.0,...,earthquake,SGC,"Marsella - Risaralda, Colombia",4.924839,-75.764090,MLr_2,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputsi
18,2026-08-29 22:09:49+00:00,OVSPOP_2833568,9.000000,2.800000,0.110000,NaN,NaN,NaN,NaN,24.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.399000,-76.337333,MLr,Hypo71,RSNC,DESTACADO\n,Event with comment different from DESTACADO
19,2026-08-30 05:02:38+00:00,SGC2026rauaxm,26.000000,1.472700,0.960000,6.400000,10.535891,10.535891,7.0,7.0,...,earthquake,SGC,"San Agustín - Huila, Colombia",2.100167,-76.529333,MLr_2,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026rauaxl
20,2026-08-30 05:02:41+00:00,SGC2026rauaxl,21.914621,2.449696,1.095312,6.726189,3.634635,4.916613,27.0,18.0,...,earthquake,SGC,"El Tambo - Cauca, Colombia",2.430138,-76.888878,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026rauaxm
21,2026-08-30 18:48:37+00:00,OVSP4910444,14.121221,2.200000,0.070000,NaN,NaN,NaN,13.0,13.0,...,earthquake,OVSP,Área de Influencia del Volcán Galeras,1.290207,-77.415121,MLr,,,,Event with comment different from DESTACADO
22,2026-08-31 15:00:28+00:00,SGC2026rdjoym,4.510000,2.565373,0.400000,2.700000,1.484924,1.484924,18.0,18.0,...,earthquake,SGC,"Panamá - Colombia , Región Fronteriza",7.527167,-77.988167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1

In [8]:
result = runner_obj.update_from_cache(events_df=result.total_events)

In [9]:
#result.duplicates

In [10]:
result.checks

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
3820,2026-03-18 15:22:57+00:00,SGC2026fkrugu,41.310000,2.821528,1.15000,0.0000,5.091169,5.091169,19.0,19.0,...,earthquake,SGC,Océano Pacífico,2.555333,-79.800333,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
5024,2026-03-23 22:19:19+00:00,USGS_us7000s76i,14.520000,4.600000,0.72000,NaN,0.039300,0.061900,NaN,57.0,...,outside of network interest,USGS,"Puerto, Chile",-20.032900,-70.950000,mwr,,,,Event with comment different from DESTACADO
5699,2026-03-26 22:53:32+00:00,SGC2026fzynny,1.000000,1.740561,0.37000,0.9000,0.707107,0.707107,14.0,14.0,...,earthquake,SGC,Colombia-Ecuador Border Region,0.793667,-77.929500,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
25336,2026-06-18 09:27:40+00:00,SGC2026lxcvaw,20.000000,2.326374,1.24000,6.2000,2.899138,2.899138,22.0,20.0,...,earthquake,SGC,Océano Pacífico,5.852167,-78.327667,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
38253,2026-08-11 09:03:38+00:00,SGC2026psffvr,4.320000,3.135464,1.17000,3.1000,2.333452,2.333452,69.0,68.0,...,earthquake,SGC,Océano Pacífico,3.054667,-79.252167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
39295,2026-08-14 13:08:08+00:00,SGC2026pyanec,45.248326,3.238456,1.06123,5.1513,2.164437,2.468013,120.0,117.0,...,earthquake,SGC,"Istmina - Chocó, Colombia",4.464816,-76.705386,MLr_1,NonLinLoc,Poveda_et_al_2018,DESTACADO\n,Event with comment different from DESTACADO
44199,2026-08-29 22:09:49+00:00,OVSPOP_2833568,9.000000,2.800000,0.11000,NaN,NaN,NaN,NaN,24.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.399000,-76.337333,MLr,Hypo71,RSNC,DESTACADO\n,Event with comment different from DESTACADO
44514,2026-08-30 18:48:37+00:00,OVSP4910444,14.121221,2.200000,0.07000,NaN,NaN,NaN,13.0,13.0,...,earthquake,OVSP,Área de Influencia del Volcán Galeras,1.290207,-77.415121,MLr,,,,Event with comment different from DESTACADO
44811,2026-08-31 15:00:28+00:00,SGC2026rdjoym,4.510000,2.565373,0.40000,2.7000,1.484924,1.484924,18.0,18.0,...,earthquake,SGC,"Panamá - Colombia , Región Fronteriza",7.527167,-77.988167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1

In [11]:
result.output

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
0,2026-03-10 05:01:27+00:00,SGC2026evfjqe,115.020000,1.659107,0.380000,5.600000,3.889087,3.889087,14.0,14.0,...,earthquake,SGC,"Onzaga - Santander, Colombia",6.221167,-72.782667,MLr_3,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026evfjyn
1,2026-03-10 05:01:29+00:00,SGC2026evfjyn,144.580000,1.735847,0.310000,3.700000,5.232590,5.232590,11.0,11.0,...,earthquake,SGC,"San Vicente de ChucurÃ­ - Santander, Colombia",6.739833,-73.395000,MLr_vmm,Hypo71,VMM,None,SSWA: Possible duplicate event of SGC2026evfjqe
2,2026-03-18 15:22:57+00:00,SGC2026fkrugu,41.310000,2.821528,1.150000,0.000000,5.091169,5.091169,19.0,19.0,...,earthquake,SGC,Océano Pacífico,2.555333,-79.800333,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
3,2026-03-23 22:19:19+00:00,USGS_us7000s76i,14.520000,4.600000,0.720000,NaN,0.039300,0.061900,NaN,57.0,...,outside of network interest,USGS,"Puerto, Chile",-20.032900,-70.950000,mwr,,,,Event with comment different from DESTACADO
4,2026-03-26 22:53:32+00:00,SGC2026fzynny,1.000000,1.740561,0.370000,0.900000,0.707107,0.707107,14.0,14.0,...,earthquake,SGC,Colombia-Ecuador Border Region,0.793667,-77.929500,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
5,2026-05-07 17:29:00+00:00,SGC2026iyqgvw,0.010000,2.094457,0.480000,6.700000,3.323402,3.323402,7.0,7.0,...,explosion,SGC,"La Jagua de Ibirico - Cesar, Colombia",9.643167,-73.413000,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgwu
6,2026-05-07 17:29:02+00:00,SGC2026iyqgwu,20.350000,2.232984,1.000000,6.500000,5.303301,5.303301,15.0,13.0,...,explosion,SGC,"Becerrill - Cesar, Colombia",9.684000,-73.341333,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgvw
7,2026-05-08 23:06:59+00:00,SGC2026jaxezo,144.820871,2.195770,1.015575,6.296250,3.534268,4.819145,49.0,45.0,...,earthquake,SGC,"Los Santos - Santander, Colombia",6.791371,-73.110256,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxfag
8,2026-05-08 23:07:02+00:00,SGC2026jaxfag,168.039062,2.139073,0.912856,10.159535,10.171115,7.821433,19.0,19.0,...,earthquake,SGC,"Arboledas - Norte de Santander, Colombia",7.534811,-72.944324,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxezo
9,2026-05-30 21:27:25+00:00,USGS2026gcdsqo,35.000000,5.600000,NaN,NaN,NaN,NaN,NaN,NaN,...,outside of network interest,USGS,"Oistins, Barbados",11.900000,-59.100000,mb,,,None,SSWA: Possible duplicate event of SGC2026kpdwsu
10,2026-05-30 21:27:28+00:00,SGC2026kpdwsu,32.385475,5.519399,1.484747,6.384253,2.480362,5.504258,140.0,125.0,...,outside of network interest,SGC,Windward Islands,12.124347,-59.531719,Mw(Mwp),LOCSAT,iasp91,None,SSWA: Possible duplicate event of USGS2026gcdsqo
11,2026-06-18 09:27:40+00:00,SGC2026lxcvaw,20.000000,2.326374,1.240000,6.200000,2.899138,2.899138,22.0,20.0,...,earthquake,SGC,Océano Pacífico,5.852167,-78.327667,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
12,2026-08-11 08:12:57+00:00,SGC2026psdoen,42.390000,1.452818,0.330000,9.600000,1.909188,1.909188,18.0,10.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.144667,-76.788333,MLr_1,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026psdocc
13,2026-08-11 08:13:00+00:00,SGC2026psdocc,54.027344,2.750620,1.297853,6.703477,3.231052,3.083073,72.0,71.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.120063,-76.769755,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026psdoen
14,2026-08-11 09:03:38+00:00,SGC2026psffvr,4.320000,3.135464,1.170000,3.100000,2.333452,2.333452,69.0,68.0,...,earthquake,SGC,Océano Pacífico,3.054667,-79.252167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
15,2026-08-14 13:08:08+00:00,SGC2026pyanec,45.248326,3.238456,1.061230,5.151300,2.164437,2.468013,120.0,117.0,...,earthquake,SGC,"Istmina - Chocó, Colombia",4.464816,-76.705386,MLr_1,NonLinLoc,Poveda_et_al_2018,DESTACADO\n,Event with comment different from DESTACADO
16,2026-08-24 05:34:33+00:00,SGC2026qputsi,88.796875,1.965782,0.842429,7.729107,5.951305,9.399577,27.0,24.0,...,earthquake,SGC,"Sipí - Chocó, Colombia",4.698529,-76.328161,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputel
17,2026-08-24 05:34:35+00:00,SGC2026qputel,101.503348,1.668413,0.742718,7.017535,4.969709,9.876757,23.0,23.0,...,earthquake,SGC,"Marsella - Risaralda, Colombia",4.924839,-75.764090,MLr_2,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputsi
18,2026-08-29 22:09:49+00:00,OVSPOP_2833568,9.000000,2.800000,0.110000,NaN,NaN,NaN,NaN,24.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.399000,-76.337333,MLr,Hypo71,RSNC,DESTACADO\n,Event with comment different from DESTACADO
19,2026-08-30 05:02:38+00:00,SGC2026rauaxm,26.000000,1.472700,0.960000,6.400000,10.535891,10.535891,7.0,7.0,...,earthquake,SGC,"San Agustín - Huila, Colombia",2.100167,-76.529333,MLr_2,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026rauaxl
20,2026-08-30 05:02:41+00:00,SGC2026rauaxl,21.914621,2.449696,1.095312,6.726189,3.634635,4.916613,27.0,18.0,...,earthquake,SGC,"El Tambo - Cauca, Colombia",2.430138,-76.888878,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026rauaxm
21,2026-08-30 18:48:37+00:00,OVSP4910444,14.121221,2.200000,0.070000,NaN,NaN,NaN,13.0,13.0,...,earthquake,OVSP,Área de Influencia del Volcán Galeras,1.290207,-77.415121,MLr,,,,Event with comment different from DESTACADO
22,2026-08-31 15:00:28+00:00,SGC2026rdjoym,4.510000,2.565373,0.400000,2.700000,1.484924,1.484924,18.0,18.0,...,earthquake,SGC,"Panamá - Colombia , Región Fronteriza",7.527167,-77.988167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1

In [13]:
# Print unique authors from the output
print(result.total_events['creationInfo_author'].unique())

['william@proc3' 'kgarcia@proc2' 'scanlocbay' 'gerard@proc3'
 'muruena@proc2' 'dcreina@proc3' 'axlopez@proc2' 'hmoreno@proc2'
 'amarin@proc3' 'seismo@proc3' 'muruena@proc3' 'dcreina@proc2'
 'william@proc2' 'kgarcia@proc3' 'axlopez@proc3' 'siscom' 'dperez@proc2'
 'scanloc' 'amarin@proc2' 'gerard@proc2' 'homreno@proc3' 'sismologo'
 'hmoreno@proc3' 'adagudelo@sismologo' 'LAKIY' 'automatic' 'dfruiz@proc2'
 'scautoloc2@sc-principal' 'scanloc_b' 'scolv@sc-principal'
 'scautoloc_reg']