# Package Tests

This notebook will make some tests to check if the package is working correctly. We will start by doing some simple TOML files to check if the package is able to read them correctly. Then we will move on to more complex tests.

To initialize any object in the package, you will need to create a TOML file with the configuration of the object you want to create. The package will read this file and create the object accordingly.

In [1]:
from src.core import runner as pyrsnc

runner_obj = pyrsnc.Runner(config_path="test.toml")

At the initialization of the Runner object, the package will read the TOML file and create the object accordingly. If the TOML file is not found or is not valid, the package will raise an error. Let's start with a simple TOML file to check if the package is able to read it correctly. The TOML file will contain the configuration of a simple object that we will create.

Any TOML file must have at least the following info:
- A database provided
- A query to be executed on the database

```toml
[[database]]
name       = "sc6"
env_file   = ".env"  # It requires the .env file at the same path as the TOML file, otherwise specify the full path to the .env file
env_prefix = "SERVER_SC6"

[[queries]]
name       = "sc6"
sql_file   = "./queries/revision.sql"
description= "Query to retrieve events from SeisComP6 database"
database   = "sc6"
```

In [2]:
print(runner_obj.list_queries())

['SeisComP3', 'SeisComP6']

In [3]:
result = runner_obj.run()

In [4]:
result.total_events

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,quality_associatedStationCount,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment
0,2026-03-17 00:00:00+00:00,USGS_nc75329017,2.000000,3.300000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,outside of network interest,USGS,"The Geysers, CA",38.829000,-122.823000,M,smi:local/manual,,None
1,2026-03-17 00:02:41+00:00,SGC2026fhroii,10.000000,1.766955,17.281041,NaN,NaN,NaN,NaN,NaN,...,NaN,not existing,SGC,"Riosucio - Caldas, Colombia",5.421100,-75.710400,MLr_2,,,None
2,2026-03-17 00:16:44+00:00,SGC2026fhsalj,9.990000,1.339800,0.260000,2.700000,0.777817,0.777817,16.0,16.0,...,NaN,earthquake,SGC,"Beltrán - Cundinamarca, Colombia",4.834333,-74.748333,MLr_2,Hypo71,RSNC,None
3,2026-03-17 00:50:53+00:00,SGC2026fhtdwg,10.000000,0.015015,6.615750,NaN,NaN,NaN,NaN,NaN,...,NaN,not locatable,SGC,"Dabeiba - Antioquia, Colombia",7.018000,-76.210000,MLr_1,,,None
4,2026-03-17 00:51:44+00:00,SGC2026fhtepm,155.890000,1.606607,0.190000,3.600000,3.818377,3.818377,6.0,6.0,...,NaN,not locatable,SGC,"Los Santos - Santander, Colombia",6.826167,-73.084500,MLr_3,Hypo71,RSNC,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42853,2026-09-05 23:13:54+00:00,SGC2026rneoou,39.703683,1.861787,0.742794,8.411041,5.636729,6.429574,16.0,16.0,...,NaN,earthquake,SGC,"Istmina - Chocó, Colombia",4.505002,-76.724773,MLr_1,NonLinLoc,Poveda_et_al_2018,None
42854,2026-09-05 23:15:40+00:00,SGC2026rnepzi,137.890067,3.133111,1.095726,5.281879,2.101876,2.686938,113.0,104.0,...,NaN,earthquake,SGC,"Lenguazaque - Cundinamarca, Colombia",5.298146,-73.720273,MLr_3,NonLinLoc,Poveda_et_al_2018,None
42855,2026-09-05 23:33:44+00:00,SGC2026rnffqx,145.140000,1.717174,0.140000,3.800000,5.161880,5.161880,6.0,6.0,...,NaN,not locatable,SGC,"Los Santos - Santander, Colombia",6.804833,-73.073667,MLr_3,Hypo71,RSNC,None
42856,2026-09-05 23:40:35+00:00,SGC2026rnflnz,135.430000,1.867111,0.270000,1.600000,1.767767,1.767767,20.0,20.0,...,NaN,earthquake,SGC,"Togüí - Boyacá, Colombia",5.864000,-73.450667,MLr_3,Hypo71,RSNC,None
42857,2026-09-05 23:50:45+00:00,SGC2026rnfuia,3.530000,1.581274,0.980000,22.500000,22.910260,22.910260,8.0,8.0,...,NaN,earthquake,SGC,"Hato Corozal - Casanare, Colombia",6.032500,-71.913333,MLr_3,Hypo71,RSNC,None

In [5]:
result.duplicates

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
25,2026-03-17 02:36:40+00:00,SGC2026fhwraz,31.848772,2.960928,1.237640,5.201036,2.996295,3.525456,77.0,64.0,...,earthquake,SGC,"Carmen del Darién (Curbaradó) - Chocó, Colombia",7.000761,-76.858903,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026fhwqwx
26,2026-03-17 02:36:42+00:00,SGC2026fhwqwx,21.540000,2.887199,0.780000,1.900000,1.131371,1.131371,37.0,37.0,...,earthquake,SGC,"Carmen del DariÃ©n (CurbaradÃ³) - ChocÃ³, Col...",6.993333,-76.889333,MLr_1,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026fhwraz
12634,2026-05-07 17:29:00+00:00,SGC2026iyqgvw,0.010000,2.094457,0.480000,6.700000,3.323402,3.323402,7.0,7.0,...,explosion,SGC,"La Jagua de Ibirico - Cesar, Colombia",9.643167,-73.413000,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgwu
12635,2026-05-07 17:29:02+00:00,SGC2026iyqgwu,20.350000,2.232984,1.000000,6.500000,5.303301,5.303301,15.0,13.0,...,explosion,SGC,"Becerrill - Cesar, Colombia",9.684000,-73.341333,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgvw
12910,2026-05-08 23:06:59+00:00,SGC2026jaxezo,144.820871,2.195770,1.015575,6.296250,3.534268,4.819145,49.0,45.0,...,earthquake,SGC,"Los Santos - Santander, Colombia",6.791371,-73.110256,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxfag
12911,2026-05-08 23:07:02+00:00,SGC2026jaxfag,168.039062,2.139073,0.912856,10.159535,10.171115,7.821433,19.0,19.0,...,earthquake,SGC,"Arboledas - Norte de Santander, Colombia",7.534811,-72.944324,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxezo
18110,2026-05-30 21:27:25+00:00,USGS2026gcdsqo,35.000000,5.600000,NaN,NaN,NaN,NaN,NaN,NaN,...,outside of network interest,USGS,"Oistins, Barbados",11.900000,-59.100000,mb,,,None,SSWA: Possible duplicate event of SGC2026kpdwsu
18111,2026-05-30 21:27:28+00:00,SGC2026kpdwsu,32.385475,5.519399,1.484747,6.384253,2.480362,5.504258,140.0,125.0,...,outside of network interest,SGC,Windward Islands,12.124347,-59.531719,Mw(Mwp),LOCSAT,iasp91,None,SSWA: Possible duplicate event of USGS2026gcdsqo
34769,2026-08-11 08:12:57+00:00,SGC2026psdoen,42.390000,1.452818,0.330000,9.600000,1.909188,1.909188,18.0,10.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.144667,-76.788333,MLr_1,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026psdocc
34770,2026-08-11 08:13:00+00:00,SGC2026psdocc,54.027344,2.750620,1.297853,6.703477,3.231052,3.083073,72.0,71.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.120063,-76.769755,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026psdoen
38789,2026-08-24 05:34:33+00:00,SGC2026qputsi,88.796875,1.965782,0.842429,7.729107,5.951305,9.399577,27.0,24.0,...,earthquake,SGC,"Sipí - Chocó, Colombia",4.698529,-76.328161,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputel
38790,2026-08-24 05:34:35+00:00,SGC2026qputel,101.503348,1.668413,0.742718,7.017535,4.969709,9.876757,23.0,23.0,...,earthquake,SGC,"Marsella - Risaralda, Colombia",4.924839,-75.764090,MLr_2,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputsi
40827,2026-08-30 05:02:38+00:00,SGC2026rauaxm,26.000000,1.472700,0.960000,6.400000,10.535891,10.535891,7.0,7.0,...,earthquake,SGC,"San Agustín - Huila, Colombia",2.100167,-76.529333,MLr_2,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026rauaxl
40828,2026-08-30 05:02:41+00:00,SGC2026rauaxl,21.914621,2.449696,1.095312,6.726189,3.634635,4.916613,27.0,18.0,...,earthquake,SGC,"El Tambo - Cauca, Colombia",2.430138,-76.888878,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026rauaxm

In [6]:
result.checks

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
20,2026-03-17 02:11:58+00:00,SGC2026fhvvtf,5.000000,1.303737,0.358825,NaN,9.224097,2.895570,8.0,8.0,...,None,SGC,"Cabrera - Cundinamarca, Colombia",3.842824,-74.524002,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
23,2026-03-17 02:31:35+00:00,SGC2026fhwmqr,369.373383,3.260283,0.034516,53.032854,38.758040,67.767965,9.0,9.0,...,None,SGC,OcÃ©ano PacÃ­fico,4.372683,-77.765800,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
57,2026-03-17 05:24:59+00:00,SGC2026ficgbp,5.245960,1.791396,0.410187,4.024052,1.766098,1.706819,23.0,23.0,...,None,SGC,"Ituango - Antioquia, Colombia",7.208091,-75.684555,M,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
111,2026-03-17 08:39:28+00:00,SGC2026fiirqx,5.000000,1.170585,0.335086,NaN,5.845750,3.304814,6.0,6.0,...,None,SGC,"Guamal - Meta, Colombia",3.975494,-74.071526,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
168,2026-03-17 13:16:29+00:00,SGC2026firwjl,182.994171,2.549044,0.190258,16.477134,7.625458,7.733702,9.0,9.0,...,None,SGC,"Puerto Triunfo - Antioquia, Colombia",5.947579,-74.819885,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
174,2026-03-17 13:54:20+00:00,SGC2026fitcze,140.174271,2.112674,0.580345,6.654127,5.608948,3.814549,18.0,18.0,...,None,SGC,"Los Santos - Santander, Colombia",6.834950,-73.168327,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
6707,2026-04-16 12:33:25+00:00,OVSP_4862039,4.040000,3.300000,0.180000,NaN,NaN,NaN,NaN,12.0,...,volcanic eruption,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.819000,-77.963333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
9355,2026-04-27 14:08:24+00:00,OVSP_4868256,19.750000,3.000000,0.050000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Túquerres - Nariño, Colombia",1.067500,-77.573167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
9553,2026-04-28 09:22:10+00:00,OVSP_4868856,22.090000,3.000000,0.060000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Túquerres - Nariño, Colombia",1.086000,-77.612167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
9572,2026-04-28 10:31:00+00:00,OVSP_4868858,4.330000,3.900000,0.100000,NaN,NaN,NaN,NaN,9.0,...,volcanic eruption,OVSP,Colombia-Ecuador Border Region,0.815500,-77.945167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
16899,2026-05-25 02:14:59+00:00,OVSPOP_2772726,9.530000,3.000000,0.020000,NaN,NaN,NaN,NaN,6.0,...,volcanic eruption,OVSPOP,"Páez (Belalcázar) - Cauca, Colombia",2.791000,-76.066333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
19317,2026-06-05 16:56:38+00:00,OVSP_4883905,7.980000,2.900000,0.140000,NaN,NaN,NaN,NaN,11.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.833000,-77.858833,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
20902,2026-06-13 19:15:39+00:00,OVSM_3331236,2.820000,3.000000,0.100000,NaN,NaN,NaN,NaN,42.0,...,volcanic eruption,OVSM,"Murillo - Tolima, Colombia",4.913167,-75.315333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
23886,2026-06-27 12:26:42+00:00,OVSP_4894913,5.700000,2.900000,0.260000,NaN,NaN,NaN,NaN,10.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.840167,-77.868167,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
24302,2026-06-29 12:11:39+00:00,OVSP_4895283,2.780000,2.800000,0.100000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.818333,-77.956000,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
28174,2026-07-16 06:57:45+00:00,OVSPA_4899096,3.183548,1.600000,0.085865,NaN,NaN,NaN,NaN,9.0,...,volcanic eruption,OVSPA,"Tufiño - Carchi, Ecuador, Colombia",0.821695,-77.936670,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
28204,2026-07-16 09:32:29+00:00,OVSP_4899103,0.870000,2.100000,0.060000,NaN,NaN,NaN,NaN,8.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.946833,-77.905000,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
30931,2026-07-28 03:06:32+00:00,OVSP_4902330,6.980000,2.000000,0.130000,NaN,NaN,NaN,NaN,13.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.867167,-77.900500,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
31234,2026-07-29 15:27:04+00:00,OVSP_4902688,9.680000,4.200000,0.070000,NaN,NaN,NaN,NaN,11.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.832333,-77.871167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
31369,2026-07-30 06:44:48+00:00,OVSP_4902794,8.060000,2.300000,0.130000,NaN,NaN,NaN,NaN,13.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.833833,-77.847333,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
33591,2026-08-07 17:49:33+00:00,OVSP_4905140,7.850000,4.800000,0.070000,NaN,NaN,NaN,NaN,13.0,...,volcanic eruption,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.826833,-77.838000,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
33597,2026-08-07 18:14:12+00:00,OVSP_4905145,7.230000,2.100000,0.330000,NaN,NaN,NaN,NaN,10.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.840167,-77.851333,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
33627,2026-08-07 20:09:20+00:00,OVSP_4905160,7.560000,2.100000,0.170000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.838833,-77.845833,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
33688,2026-08-08 02:11:55+00:00,OVSP_4905236,7.850000,4.300000,0.150000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.838333,-77.844667,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
33689,2026-08-08 02:13:50+00:00,OVSP_4905239,7.580000,2.500000,0.120000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.834167,-77.846167,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
38650,2026-08-23 19:52:28+00:00,OVSP2026mjoacv,10.000000,2.600000,NaN,NaN,NaN,NaN,NaN,NaN,...,earthquake,OVSP,"Nariño - Nariño, Colombia - Area De Influencia...",1.290000,-77.300000,mb,,,None,Incorrect magnitude type for zone2
39109,2026-08-25 03:04:50+00:00,OVSP2026jtqaoa,15.000000,2.100000,NaN,NaN,NaN,NaN,NaN,NaN,...,earthquake,OVSP,"Consacá - Nariño, Colombia",1.160000,-77.450000,mb,,,None,Incorrect magnitude type for zone2
40495,2026-08-29 06:23:54+00:00,OVSP2026tevxos,19.000000,2.400000,NaN,NaN,NaN,NaN,NaN,NaN,...,volcanic eruption,OVSP,"Aldana, Nariño - Área de Influencia del Volcán...",0.910000,-77.710000,ML,,,DESTACADO,Incorrect magnitude type for zone2
40676,2026-08-29 18:35:34+00:00,OVSP4910203,7.252670,2.700000,0.160000,NaN,NaN,NaN,18.0,18.0,...,volcanic eruption,OVSP,Área de Influencia del Volcán Galeras,1.251381,-77.337377,MLr,,,DESTACADO,Incorrect magnitude type for zone2
40714,2026-08-29 21:21:17+00:00,OVSPOP_2833532,9.720000,3.900000,0.140000,NaN,NaN,NaN,NaN,25.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.394667,-76.333833,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
40722,2026-08-29 21:56:28+00:00,OVSPOP2026qvubbk,9.000000,3.100000,0.100000,NaN,NaN,NaN,12.0,12.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.400000,-76.340000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
40728,2026-08-29 22:09:49+00:00,OVSPOP_2833568,9.000000,2.800000,0.110000,NaN,NaN,NaN,NaN,24.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.399000,-76.337333,MLr,Hypo71,RSNC,DESTACADO\n,Incorrect magnitude type for zone2
40741,2026-08-29 23:18:36+00:00,OVSPOP_2833606,9.300000,4.100000,0.090000,NaN,NaN,NaN,23.0,23.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.395160,-76.338000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
40780,2026-08-30 02:11:47+00:00,SGC2026raojrj,8.300000,2.900000,0.100000,NaN,NaN,NaN,21.0,21.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.392333,-76.337000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
40801,2026-08-30 03:41:01+00:00,OVSPOP_2833724,10.000000,2.600000,0.070000,NaN,NaN,NaN,19.0,19.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.392000,-76.331667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
40817,2026-08-30 04:37:53+00:00,OVSPOP_2833775,12.000000,4.300000,0.070000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.416500,-76.320667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
40835,2026-08-30 05:29:21+00:00,OVSPOP_2833846,10.000000,2.000000,0.070000,NaN,NaN,NaN,22.0,22.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.395667,-76.331333,MLr,,,DESTACADO,Incorrect magnitude type for zone2
41043,2026-08-30 18:48:37+00:00,OVSP4910444,14.121221,2.200000,0.070000,NaN,NaN,NaN,13.0,13.0,...,earthquake,OVSP,Área de Influencia del Volcán Galeras,1.290207,-77.415121,MLr,,,,Incorrect magnitude type for zone2
41154,2026-08-31 02:43:54+00:00,OVSPOP_2834637,10.000000,2.500000,0.060000,NaN,NaN,NaN,18.0,18.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.398333,-76.334667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
41237,2026-08-31 08:21:44+00:00,OVSPOP_2834831,9.200000,3.200000,0.070000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Área En Litigio Limites (Puracé - Cauca, Colombia",2.385330,-76.336660,MLr,,,DESTACADO,Incorrect magnitude type for zone2
42501,2026-09-04 19:29:56+00:00,OVSPOP2836980,10.860000,2.300000,0.070000,NaN,NaN,NaN,19.0,19.0,...,volcanic eruption,OVSPOP,"Inzá - Cauca, Colombia - Área de Influencia de...",2.403500,-76.319667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
42520,2026-09-04 20:24:21+00:00,OVSP4912495,8.000000,2.200000,0.050000,NaN,NaN,NaN,11.0,11.0,...,earthquake,OVSP,"Pasto - Nariño, Colombia - Área de Influencia ...",1.280000,-77.320000,MLr,,,None,Incorrect magnitude type for zone2
42771,2026-09-05 18:46:32+00:00,SGC2026rmvsdy,8.700000,3.100000,0.080000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.400000,-76.300000,MLr,,,DESTACADO,Incorrect magnitude type for zone2

In [7]:
result.output

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
0,2026-03-17 02:11:58+00:00,SGC2026fhvvtf,5.000000,1.303737,0.358825,NaN,9.224097,2.895570,8.0,8.0,...,None,SGC,"Cabrera - Cundinamarca, Colombia",3.842824,-74.524002,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
1,2026-03-17 02:31:35+00:00,SGC2026fhwmqr,369.373383,3.260283,0.034516,53.032854,38.758040,67.767965,9.0,9.0,...,None,SGC,OcÃ©ano PacÃ­fico,4.372683,-77.765800,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
2,2026-03-17 02:36:40+00:00,SGC2026fhwraz,31.848772,2.960928,1.237640,5.201036,2.996295,3.525456,77.0,64.0,...,earthquake,SGC,"Carmen del Darién (Curbaradó) - Chocó, Colombia",7.000761,-76.858903,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026fhwqwx
3,2026-03-17 02:36:42+00:00,SGC2026fhwqwx,21.540000,2.887199,0.780000,1.900000,1.131371,1.131371,37.0,37.0,...,earthquake,SGC,"Carmen del DariÃ©n (CurbaradÃ³) - ChocÃ³, Col...",6.993333,-76.889333,MLr_1,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026fhwraz
4,2026-03-17 05:24:59+00:00,SGC2026ficgbp,5.245960,1.791396,0.410187,4.024052,1.766098,1.706819,23.0,23.0,...,None,SGC,"Ituango - Antioquia, Colombia",7.208091,-75.684555,M,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
5,2026-03-17 08:39:28+00:00,SGC2026fiirqx,5.000000,1.170585,0.335086,NaN,5.845750,3.304814,6.0,6.0,...,None,SGC,"Guamal - Meta, Colombia",3.975494,-74.071526,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
6,2026-03-17 13:16:29+00:00,SGC2026firwjl,182.994171,2.549044,0.190258,16.477134,7.625458,7.733702,9.0,9.0,...,None,SGC,"Puerto Triunfo - Antioquia, Colombia",5.947579,-74.819885,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
7,2026-03-17 13:54:20+00:00,SGC2026fitcze,140.174271,2.112674,0.580345,6.654127,5.608948,3.814549,18.0,18.0,...,None,SGC,"Los Santos - Santander, Colombia",6.834950,-73.168327,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
8,2026-04-16 12:33:25+00:00,OVSP_4862039,4.040000,3.300000,0.180000,NaN,NaN,NaN,NaN,12.0,...,volcanic eruption,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.819000,-77.963333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
9,2026-04-27 14:08:24+00:00,OVSP_4868256,19.750000,3.000000,0.050000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Túquerres - Nariño, Colombia",1.067500,-77.573167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
10,2026-04-28 09:22:10+00:00,OVSP_4868856,22.090000,3.000000,0.060000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Túquerres - Nariño, Colombia",1.086000,-77.612167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
11,2026-04-28 10:31:00+00:00,OVSP_4868858,4.330000,3.900000,0.100000,NaN,NaN,NaN,NaN,9.0,...,volcanic eruption,OVSP,Colombia-Ecuador Border Region,0.815500,-77.945167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
12,2026-05-07 17:29:00+00:00,SGC2026iyqgvw,0.010000,2.094457,0.480000,6.700000,3.323402,3.323402,7.0,7.0,...,explosion,SGC,"La Jagua de Ibirico - Cesar, Colombia",9.643167,-73.413000,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgwu
13,2026-05-07 17:29:02+00:00,SGC2026iyqgwu,20.350000,2.232984,1.000000,6.500000,5.303301,5.303301,15.0,13.0,...,explosion,SGC,"Becerrill - Cesar, Colombia",9.684000,-73.341333,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgvw
14,2026-05-08 23:06:59+00:00,SGC2026jaxezo,144.820871,2.195770,1.015575,6.296250,3.534268,4.819145,49.0,45.0,...,earthquake,SGC,"Los Santos - Santander, Colombia",6.791371,-73.110256,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxfag
15,2026-05-08 23:07:02+00:00,SGC2026jaxfag,168.039062,2.139073,0.912856,10.159535,10.171115,7.821433,19.0,19.0,...,earthquake,SGC,"Arboledas - Norte de Santander, Colombia",7.534811,-72.944324,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxezo
16,2026-05-25 02:14:59+00:00,OVSPOP_2772726,9.530000,3.000000,0.020000,NaN,NaN,NaN,NaN,6.0,...,volcanic eruption,OVSPOP,"Páez (Belalcázar) - Cauca, Colombia",2.791000,-76.066333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
17,2026-05-30 21:27:25+00:00,USGS2026gcdsqo,35.000000,5.600000,NaN,NaN,NaN,NaN,NaN,NaN,...,outside of network interest,USGS,"Oistins, Barbados",11.900000,-59.100000,mb,,,None,SSWA: Possible duplicate event of SGC2026kpdwsu
18,2026-05-30 21:27:28+00:00,SGC2026kpdwsu,32.385475,5.519399,1.484747,6.384253,2.480362,5.504258,140.0,125.0,...,outside of network interest,SGC,Windward Islands,12.124347,-59.531719,Mw(Mwp),LOCSAT,iasp91,None,SSWA: Possible duplicate event of USGS2026gcdsqo
19,2026-06-05 16:56:38+00:00,OVSP_4883905,7.980000,2.900000,0.140000,NaN,NaN,NaN,NaN,11.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.833000,-77.858833,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
20,2026-06-13 19:15:39+00:00,OVSM_3331236,2.820000,3.000000,0.100000,NaN,NaN,NaN,NaN,42.0,...,volcanic eruption,OVSM,"Murillo - Tolima, Colombia",4.913167,-75.315333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
21,2026-06-27 12:26:42+00:00,OVSP_4894913,5.700000,2.900000,0.260000,NaN,NaN,NaN,NaN,10.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.840167,-77.868167,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
22,2026-06-29 12:11:39+00:00,OVSP_4895283,2.780000,2.800000,0.100000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.818333,-77.956000,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
23,2026-07-16 06:57:45+00:00,OVSPA_4899096,3.183548,1.600000,0.085865,NaN,NaN,NaN,NaN,9.0,...,volcanic eruption,OVSPA,"Tufiño - Carchi, Ecuador, Colombia",0.821695,-77.936670,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
24,2026-07-16 09:32:29+00:00,OVSP_4899103,0.870000,2.100000,0.060000,NaN,NaN,NaN,NaN,8.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.946833,-77.905000,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
25,2026-07-28 03:06:32+00:00,OVSP_4902330,6.980000,2.000000,0.130000,NaN,NaN,NaN,NaN,13.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.867167,-77.900500,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
26,2026-07-29 15:27:04+00:00,OVSP_4902688,9.680000,4.200000,0.070000,NaN,NaN,NaN,NaN,11.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.832333,-77.871167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
27,2026-07-30 06:44:48+00:00,OVSP_4902794,8.060000,2.300000,0.130000,NaN,NaN,NaN,NaN,13.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.833833,-77.847333,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
28,2026-08-07 17:49:33+00:00,OVSP_4905140,7.850000,4.800000,0.070000,NaN,NaN,NaN,NaN,13.0,...,volcanic eruption,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.826833,-77.838000,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
29,2026-08-07 18:14:12+00:00,OVSP_4905145,7.230000,2.100000,0.330000,NaN,NaN,NaN,NaN,10.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.840167,-77.851333,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
30,2026-08-07 20:09:20+00:00,OVSP_4905160,7.560000,2.100000,0.170000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.838833,-77.845833,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
31,2026-08-08 02:11:55+00:00,OVSP_4905236,7.850000,4.300000,0.150000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.838333,-77.844667,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
32,2026-08-08 02:13:50+00:00,OVSP_4905239,7.580000,2.500000,0.120000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.834167,-77.846167,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
33,2026-08-11 08:12:57+00:00,SGC2026psdoen,42.390000,1.452818,0.330000,9.600000,1.909188,1.909188,18.0,10.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.144667,-76.788333,MLr_1,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026psdocc
34,2026-08-11 08:13:00+00:00,SGC2026psdocc,54.027344,2.750620,1.297853,6.703477,3.231052,3.083073,72.0,71.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.120063,-76.769755,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026psdoen
35,2026-08-23 19:52:28+00:00,OVSP2026mjoacv,10.000000,2.600000,NaN,NaN,NaN,NaN,NaN,NaN,...,earthquake,OVSP,"Nariño - Nariño, Colombia - Area De Influencia...",1.290000,-77.300000,mb,,,None,Incorrect magnitude type for zone2
36,2026-08-24 05:34:33+00:00,SGC2026qputsi,88.796875,1.965782,0.842429,7.729107,5.951305,9.399577,27.0,24.0,...,earthquake,SGC,"Sipí - Chocó, Colombia",4.698529,-76.328161,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputel
37,2026-08-24 05:34:35+00:00,SGC2026qputel,101.503348,1.668413,0.742718,7.017535,4.969709,9.876757,23.0,23.0,...,earthquake,SGC,"Marsella - Risaralda, Colombia",4.924839,-75.764090,MLr_2,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputsi
38,2026-08-25 03:04:50+00:00,OVSP2026jtqaoa,15.000000,2.100000,NaN,NaN,NaN,NaN,NaN,NaN,...,earthquake,OVSP,"Consacá - Nariño, Colombia",1.160000,-77.450000,mb,,,None,Incorrect magnitude type for zone2
39,2026-08-29 06:23:54+00:00,OVSP2026tevxos,19.000000,2.400000,NaN,NaN,NaN,NaN,NaN,NaN,...,volcanic eruption,OVSP,"Aldana, Nariño - Área de Influencia del Volcán...",0.910000,-77.710000,ML,,,DESTACADO,Incorrect magnitude type for zone2
40,2026-08-29 18:35:34+00:00,OVSP4910203,7.252670,2.700000,0.160000,NaN,NaN,NaN,18.0,18.0,...,volcanic eruption,OVSP,Área de Influencia del Volcán Galeras,1.251381,-77.337377,MLr,,,DESTACADO,Incorrect magnitude type for zone2
41,2026-08-29 21:21:17+00:00,OVSPOP_2833532,9.720000,3.900000,0.140000,NaN,NaN,NaN,NaN,25.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.394667,-76.333833,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
42,2026-08-29 21:56:28+00:00,OVSPOP2026qvubbk,9.000000,3.100000,0.100000,NaN,NaN,NaN,12.0,12.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.400000,-76.340000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
43,2026-08-29 22:09:49+00:00,OVSPOP_2833568,9.000000,2.800000,0.110000,NaN,NaN,NaN,NaN,24.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.399000,-76.337333,MLr,Hypo71,RSNC,DESTACADO\n,Incorrect magnitude type for zone2
44,2026-08-29 23:18:36+00:00,OVSPOP_2833606,9.300000,4.100000,0.090000,NaN,NaN,NaN,23.0,23.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.395160,-76.338000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
45,2026-08-30 02:11:47+00:00,SGC2026raojrj,8.300000,2.900000,0.100000,NaN,NaN,NaN,21.0,21.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.392333,-76.337000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
46,2026-08-30 03:41:01+00:00,OVSPOP_2833724,10.000000,2.600000,0.070000,NaN,NaN,NaN,19.0,19.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.392000,-76.331667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
47,2026-08-30 04:37:53+00:00,OVSPOP_2833775,12.000000,4.300000,0.070000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.416500,-76.320667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
48,2026-08-30 05:02:38+00:00,SGC2026rauaxm,26.000000,1.472700,0.960000,6.400000,10.535891,10.535891,7.0,7.0,...,earthquake,SGC,"San Agustín - Huila, Colombia",2.100167,-76.529333,MLr_2,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026rauaxl
49,2026-08-30 05:02:41+00:00,SGC2026rauaxl,21.914621,2.449696,1.095312,6.726189,3.634635,4.916613,27.0,18.0,...,earthquake,SGC,"El Tambo - Cauca, Colombia",2.430138,-76.888878,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026rauaxm
50,2026-08-30 05:29:21+00:00,OVSPOP_2833846,10.000000,2.000000,0.070000,NaN,NaN,NaN,22.0,22.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.395667,-76.331333,MLr,,,DESTACADO,Incorrect magnitude type for zone2
51,2026-08-30 18:48:37+00:00,OVSP4910444,14.121221,2.200000,0.070000,NaN,NaN,NaN,13.0,13.0,...,earthquake,OVSP,Área de Influencia del Volcán Galeras,1.290207,-77.415121,MLr,,,,Incorrect magnitude type for zone2
52,2026-08-31 02:43:54+00:00,OVSPOP_2834637,10.000000,2.500000,0.060000,NaN,NaN,NaN,18.0,18.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.398333,-76.334667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
53,2026-08-31 08:21:44+00:00,OVSPOP_2834831,9.200000,3.200000,0.070000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Área En Litigio Limites (Puracé - Cauca, Colombia",2.385330,-76.336660,MLr,,,DESTACADO,Incorrect magnitude type for zone2
54,2026-09-04 19:29:56+00:00,OVSPOP2836980,10.860000,2.300000,0.070000,NaN,NaN,NaN,19.0,19.0,...,volcanic eruption,OVSPOP,"Inzá - Cauca, Colombia - Área de Influencia de...",2.403500,-76.319667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
55,2026-09-04 20:24:21+00:00,OVSP4912495,8.000000,2.200000,0.050000,NaN,NaN,NaN,11.0,11.0,...,earthquake,OVSP,"Pasto - Nariño, Colombia - Área de Influencia ...",1.280000,-77.320000,MLr,,,None,Incorrect magnitude type for zone2
56,2026-09-05 18:46:32+00:00,SGC2026rmvsdy,8.700000,3.100000,0.080000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.400000,-76.300000,MLr,,,DESTACADO,Incorrect magnitude type for zone2

In [19]:
result = runner_obj.update_from_cache(events_df=result.total_events)

Reloading configuration from TOML...
Re-evaluating checks...
New checks configuration: [{'name': 'Incorrect magnitude type for zone1', 'logic': 'and', 'conditions': [{'rule_type': 'category', 'column': 'event_type', 'mode': 'not_in', 'values': ['not existing', 'not locatable']}, {'rule_type': 'category', 'column': 'creationInfo_agencyID', 'mode': 'in', 'values': 'SGC'}], 'groups': [{'logic': 'xor', 'description': 'Correspondence between zone1 and magnitude MLr_1', 'conditions': [{'rule_type': 'polygon', 'lat_col': 'latitude_value', 'lon_col': 'longitude_value', 'mode': 'inside', 'polygon': 'zone1'}, {'rule_type': 'category', 'column': 'magnitude_type', 'mode': 'in', 'values': 'MLr_1'}]}, {'logic': 'and', 'negate': True, 'description': 'Not a DESTACADO event with magnitude Mw', 'conditions': [{'rule_type': 'category', 'column': 'comment', 'mode': 'in', 'values': 'DESTACADO'}, {'rule_type': 'category', 'column': 'magnitude_type', 'mode': 'in', 'values': 'Mw'}]}]}, {'name': 'Incorrect magnitude type for zone2', 'logic': 'and', 'conditions': [{'rule_type': 'category', 'column': 'event_type', 'mode': 'not_in', 'values': ['not existing', 'not locatable']}, {'rule_type': 'category', 'column': 'creationInfo_agencyID', 'mode': 'in', 'values': ['SGC']}], 'groups': [{'logic': 'xor', 'description': 'Correspondence between zone2 and magnitude MLr_2', 'groups': [{'logic': 'and', 'description': 'Event inside zone2 and outside VMM', 'conditions': [{'rule_type': 'polygon', 'lat_col': 'latitude_value', 'lon_col': 'longitude_value', 'mode': 'inside', 'polygon': 'zone2'}, {'rule_type': 'polygon', 'lat_col': 'latitude_value', 'lon_col': 'longitude_value', 'mode': 'outside', 'polygon': 'vmm'}]}], 'conditions': [{'rule_type': 'category', 'column': 'magnitude_type', 'mode': 'in', 'values': 'MLr_2'}]}, {'logic': 'and', 'negate': True, 'description': 'Not a DESTACADO event with magnitude Mw', 'conditions': [{'rule_type': 'category', 'column': 'comment', 'mode': 'in', 'values': 'DESTACADO'}, {'rule_type': 'category', 'column': 'magnitude_type', 'mode': 'in', 'values': 'Mw'}]}]}, {'name': 'Event with comment different from DESTACADO', 'logic': 'and', 'conditions': [{'rule_type': 'category', 'column': 'comment', 'mode': 'not_in', 'values': 'DESTACADO'}, {'rule_type': 'category', 'column': 'comment', 'mode': 'is_not_null'}]}]

/home/keneth/Documents/Academic_Projects/Revision_Sismicidad_SGC/src/core/runner.py:245: UserWarning: Check 'Event with comment different from DESTACADO' raised an error and was skipped: Unsupported category mode: 'is_not_null'
  polygon_cache=polygon_cache,

In [9]:
#result.duplicates

In [20]:
result.checks

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
20,2026-03-17 02:11:58+00:00,SGC2026fhvvtf,5.000000,1.303737,0.358825,NaN,9.224097,2.895570,8.0,8.0,...,None,SGC,"Cabrera - Cundinamarca, Colombia",3.842824,-74.524002,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
23,2026-03-17 02:31:35+00:00,SGC2026fhwmqr,369.373383,3.260283,0.034516,53.032854,38.758040,67.767965,9.0,9.0,...,None,SGC,OcÃ©ano PacÃ­fico,4.372683,-77.765800,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone1; Incorrect ...
57,2026-03-17 05:24:59+00:00,SGC2026ficgbp,5.245960,1.791396,0.410187,4.024052,1.766098,1.706819,23.0,23.0,...,None,SGC,"Ituango - Antioquia, Colombia",7.208091,-75.684555,M,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
111,2026-03-17 08:39:28+00:00,SGC2026fiirqx,5.000000,1.170585,0.335086,NaN,5.845750,3.304814,6.0,6.0,...,None,SGC,"Guamal - Meta, Colombia",3.975494,-74.071526,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
168,2026-03-17 13:16:29+00:00,SGC2026firwjl,182.994171,2.549044,0.190258,16.477134,7.625458,7.733702,9.0,9.0,...,None,SGC,"Puerto Triunfo - Antioquia, Colombia",5.947579,-74.819885,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
174,2026-03-17 13:54:20+00:00,SGC2026fitcze,140.174271,2.112674,0.580345,6.654127,5.608948,3.814549,18.0,18.0,...,None,SGC,"Los Santos - Santander, Colombia",6.834950,-73.168327,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
349,2026-03-18 15:22:57+00:00,SGC2026fkrugu,41.310000,2.821528,1.150000,0.000000,5.091169,5.091169,19.0,19.0,...,earthquake,SGC,Océano Pacífico,2.555333,-79.800333,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
2228,2026-03-26 22:53:32+00:00,SGC2026fzynny,1.000000,1.740561,0.370000,0.900000,0.707107,0.707107,14.0,14.0,...,earthquake,SGC,Colombia-Ecuador Border Region,0.793667,-77.929500,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
21865,2026-06-18 09:27:40+00:00,SGC2026lxcvaw,20.000000,2.326374,1.240000,6.200000,2.899138,2.899138,22.0,20.0,...,earthquake,SGC,Océano Pacífico,5.852167,-78.327667,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
34782,2026-08-11 09:03:38+00:00,SGC2026psffvr,4.320000,3.135464,1.170000,3.100000,2.333452,2.333452,69.0,68.0,...,earthquake,SGC,Océano Pacífico,3.054667,-79.252167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1
41340,2026-08-31 15:00:28+00:00,SGC2026rdjoym,4.510000,2.565373,0.400000,2.700000,1.484924,1.484924,18.0,18.0,...,earthquake,SGC,"Panamá - Colombia , Región Fronteriza",7.527167,-77.988167,MLr_1,Hypo71,RSNC,None,Incorrect magnitude type for zone1

In [11]:
result.output

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment,Observations
0,2026-03-17 02:11:58+00:00,SGC2026fhvvtf,5.000000,1.303737,0.358825,NaN,9.224097,2.895570,8.0,8.0,...,None,SGC,"Cabrera - Cundinamarca, Colombia",3.842824,-74.524002,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
1,2026-03-17 02:31:35+00:00,SGC2026fhwmqr,369.373383,3.260283,0.034516,53.032854,38.758040,67.767965,9.0,9.0,...,None,SGC,OcÃ©ano PacÃ­fico,4.372683,-77.765800,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
2,2026-03-17 02:36:40+00:00,SGC2026fhwraz,31.848772,2.960928,1.237640,5.201036,2.996295,3.525456,77.0,64.0,...,earthquake,SGC,"Carmen del Darién (Curbaradó) - Chocó, Colombia",7.000761,-76.858903,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026fhwqwx
3,2026-03-17 02:36:42+00:00,SGC2026fhwqwx,21.540000,2.887199,0.780000,1.900000,1.131371,1.131371,37.0,37.0,...,earthquake,SGC,"Carmen del DariÃ©n (CurbaradÃ³) - ChocÃ³, Col...",6.993333,-76.889333,MLr_1,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026fhwraz
4,2026-03-17 05:24:59+00:00,SGC2026ficgbp,5.245960,1.791396,0.410187,4.024052,1.766098,1.706819,23.0,23.0,...,None,SGC,"Ituango - Antioquia, Colombia",7.208091,-75.684555,M,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
5,2026-03-17 08:39:28+00:00,SGC2026fiirqx,5.000000,1.170585,0.335086,NaN,5.845750,3.304814,6.0,6.0,...,None,SGC,"Guamal - Meta, Colombia",3.975494,-74.071526,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
6,2026-03-17 13:16:29+00:00,SGC2026firwjl,182.994171,2.549044,0.190258,16.477134,7.625458,7.733702,9.0,9.0,...,None,SGC,"Puerto Triunfo - Antioquia, Colombia",5.947579,-74.819885,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
7,2026-03-17 13:54:20+00:00,SGC2026fitcze,140.174271,2.112674,0.580345,6.654127,5.608948,3.814549,18.0,18.0,...,None,SGC,"Los Santos - Santander, Colombia",6.834950,-73.168327,MLr_2,LOCSAT,iasp91,None,Incorrect magnitude type for zone2
8,2026-04-16 12:33:25+00:00,OVSP_4862039,4.040000,3.300000,0.180000,NaN,NaN,NaN,NaN,12.0,...,volcanic eruption,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.819000,-77.963333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
9,2026-04-27 14:08:24+00:00,OVSP_4868256,19.750000,3.000000,0.050000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Túquerres - Nariño, Colombia",1.067500,-77.573167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
10,2026-04-28 09:22:10+00:00,OVSP_4868856,22.090000,3.000000,0.060000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Túquerres - Nariño, Colombia",1.086000,-77.612167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
11,2026-04-28 10:31:00+00:00,OVSP_4868858,4.330000,3.900000,0.100000,NaN,NaN,NaN,NaN,9.0,...,volcanic eruption,OVSP,Colombia-Ecuador Border Region,0.815500,-77.945167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
12,2026-05-07 17:29:00+00:00,SGC2026iyqgvw,0.010000,2.094457,0.480000,6.700000,3.323402,3.323402,7.0,7.0,...,explosion,SGC,"La Jagua de Ibirico - Cesar, Colombia",9.643167,-73.413000,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgwu
13,2026-05-07 17:29:02+00:00,SGC2026iyqgwu,20.350000,2.232984,1.000000,6.500000,5.303301,5.303301,15.0,13.0,...,explosion,SGC,"Becerrill - Cesar, Colombia",9.684000,-73.341333,MLr_4,Hypo71,modelCesar2,None,SSWA: Possible duplicate event of SGC2026iyqgvw
14,2026-05-08 23:06:59+00:00,SGC2026jaxezo,144.820871,2.195770,1.015575,6.296250,3.534268,4.819145,49.0,45.0,...,earthquake,SGC,"Los Santos - Santander, Colombia",6.791371,-73.110256,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxfag
15,2026-05-08 23:07:02+00:00,SGC2026jaxfag,168.039062,2.139073,0.912856,10.159535,10.171115,7.821433,19.0,19.0,...,earthquake,SGC,"Arboledas - Norte de Santander, Colombia",7.534811,-72.944324,MLr_3,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026jaxezo
16,2026-05-25 02:14:59+00:00,OVSPOP_2772726,9.530000,3.000000,0.020000,NaN,NaN,NaN,NaN,6.0,...,volcanic eruption,OVSPOP,"Páez (Belalcázar) - Cauca, Colombia",2.791000,-76.066333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
17,2026-05-30 21:27:25+00:00,USGS2026gcdsqo,35.000000,5.600000,NaN,NaN,NaN,NaN,NaN,NaN,...,outside of network interest,USGS,"Oistins, Barbados",11.900000,-59.100000,mb,,,None,SSWA: Possible duplicate event of SGC2026kpdwsu
18,2026-05-30 21:27:28+00:00,SGC2026kpdwsu,32.385475,5.519399,1.484747,6.384253,2.480362,5.504258,140.0,125.0,...,outside of network interest,SGC,Windward Islands,12.124347,-59.531719,Mw(Mwp),LOCSAT,iasp91,None,SSWA: Possible duplicate event of USGS2026gcdsqo
19,2026-06-05 16:56:38+00:00,OVSP_4883905,7.980000,2.900000,0.140000,NaN,NaN,NaN,NaN,11.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.833000,-77.858833,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
20,2026-06-13 19:15:39+00:00,OVSM_3331236,2.820000,3.000000,0.100000,NaN,NaN,NaN,NaN,42.0,...,volcanic eruption,OVSM,"Murillo - Tolima, Colombia",4.913167,-75.315333,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
21,2026-06-27 12:26:42+00:00,OVSP_4894913,5.700000,2.900000,0.260000,NaN,NaN,NaN,NaN,10.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.840167,-77.868167,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
22,2026-06-29 12:11:39+00:00,OVSP_4895283,2.780000,2.800000,0.100000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.818333,-77.956000,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
23,2026-07-16 06:57:45+00:00,OVSPA_4899096,3.183548,1.600000,0.085865,NaN,NaN,NaN,NaN,9.0,...,volcanic eruption,OVSPA,"Tufiño - Carchi, Ecuador, Colombia",0.821695,-77.936670,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
24,2026-07-16 09:32:29+00:00,OVSP_4899103,0.870000,2.100000,0.060000,NaN,NaN,NaN,NaN,8.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.946833,-77.905000,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
25,2026-07-28 03:06:32+00:00,OVSP_4902330,6.980000,2.000000,0.130000,NaN,NaN,NaN,NaN,13.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.867167,-77.900500,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
26,2026-07-29 15:27:04+00:00,OVSP_4902688,9.680000,4.200000,0.070000,NaN,NaN,NaN,NaN,11.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.832333,-77.871167,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
27,2026-07-30 06:44:48+00:00,OVSP_4902794,8.060000,2.300000,0.130000,NaN,NaN,NaN,NaN,13.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.833833,-77.847333,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
28,2026-08-07 17:49:33+00:00,OVSP_4905140,7.850000,4.800000,0.070000,NaN,NaN,NaN,NaN,13.0,...,volcanic eruption,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.826833,-77.838000,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
29,2026-08-07 18:14:12+00:00,OVSP_4905145,7.230000,2.100000,0.330000,NaN,NaN,NaN,NaN,10.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.840167,-77.851333,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
30,2026-08-07 20:09:20+00:00,OVSP_4905160,7.560000,2.100000,0.170000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Tufiño - Carchi, Ecuador, Colombia",0.838833,-77.845833,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
31,2026-08-08 02:11:55+00:00,OVSP_4905236,7.850000,4.300000,0.150000,NaN,NaN,NaN,NaN,10.0,...,volcanic eruption,OVSP,"Cumbal - Nariño, Colombia",0.838333,-77.844667,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
32,2026-08-08 02:13:50+00:00,OVSP_4905239,7.580000,2.500000,0.120000,NaN,NaN,NaN,NaN,11.0,...,earthquake,OVSP,"Cumbal - Nariño, Colombia",0.834167,-77.846167,MLr,Hypo71,RSNC,None,Incorrect magnitude type for zone2
33,2026-08-11 08:12:57+00:00,SGC2026psdoen,42.390000,1.452818,0.330000,9.600000,1.909188,1.909188,18.0,10.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.144667,-76.788333,MLr_1,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026psdocc
34,2026-08-11 08:13:00+00:00,SGC2026psdocc,54.027344,2.750620,1.297853,6.703477,3.231052,3.083073,72.0,71.0,...,earthquake,SGC,"El Litoral del San Juán (Docordó) - Chocó, Col...",4.120063,-76.769755,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026psdoen
35,2026-08-23 19:52:28+00:00,OVSP2026mjoacv,10.000000,2.600000,NaN,NaN,NaN,NaN,NaN,NaN,...,earthquake,OVSP,"Nariño - Nariño, Colombia - Area De Influencia...",1.290000,-77.300000,mb,,,None,Incorrect magnitude type for zone2
36,2026-08-24 05:34:33+00:00,SGC2026qputsi,88.796875,1.965782,0.842429,7.729107,5.951305,9.399577,27.0,24.0,...,earthquake,SGC,"Sipí - Chocó, Colombia",4.698529,-76.328161,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputel
37,2026-08-24 05:34:35+00:00,SGC2026qputel,101.503348,1.668413,0.742718,7.017535,4.969709,9.876757,23.0,23.0,...,earthquake,SGC,"Marsella - Risaralda, Colombia",4.924839,-75.764090,MLr_2,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026qputsi
38,2026-08-25 03:04:50+00:00,OVSP2026jtqaoa,15.000000,2.100000,NaN,NaN,NaN,NaN,NaN,NaN,...,earthquake,OVSP,"Consacá - Nariño, Colombia",1.160000,-77.450000,mb,,,None,Incorrect magnitude type for zone2
39,2026-08-29 06:23:54+00:00,OVSP2026tevxos,19.000000,2.400000,NaN,NaN,NaN,NaN,NaN,NaN,...,volcanic eruption,OVSP,"Aldana, Nariño - Área de Influencia del Volcán...",0.910000,-77.710000,ML,,,DESTACADO,Incorrect magnitude type for zone2
40,2026-08-29 18:35:34+00:00,OVSP4910203,7.252670,2.700000,0.160000,NaN,NaN,NaN,18.0,18.0,...,volcanic eruption,OVSP,Área de Influencia del Volcán Galeras,1.251381,-77.337377,MLr,,,DESTACADO,Incorrect magnitude type for zone2
41,2026-08-29 21:21:17+00:00,OVSPOP_2833532,9.720000,3.900000,0.140000,NaN,NaN,NaN,NaN,25.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.394667,-76.333833,MLr,Hypo71,RSNC,DESTACADO,Incorrect magnitude type for zone2
42,2026-08-29 21:56:28+00:00,OVSPOP2026qvubbk,9.000000,3.100000,0.100000,NaN,NaN,NaN,12.0,12.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.400000,-76.340000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
43,2026-08-29 22:09:49+00:00,OVSPOP_2833568,9.000000,2.800000,0.110000,NaN,NaN,NaN,NaN,24.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.399000,-76.337333,MLr,Hypo71,RSNC,DESTACADO\n,Incorrect magnitude type for zone2
44,2026-08-29 23:18:36+00:00,OVSPOP_2833606,9.300000,4.100000,0.090000,NaN,NaN,NaN,23.0,23.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.395160,-76.338000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
45,2026-08-30 02:11:47+00:00,SGC2026raojrj,8.300000,2.900000,0.100000,NaN,NaN,NaN,21.0,21.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.392333,-76.337000,MLr,,,DESTACADO,Incorrect magnitude type for zone2
46,2026-08-30 03:41:01+00:00,OVSPOP_2833724,10.000000,2.600000,0.070000,NaN,NaN,NaN,19.0,19.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.392000,-76.331667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
47,2026-08-30 04:37:53+00:00,OVSPOP_2833775,12.000000,4.300000,0.070000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.416500,-76.320667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
48,2026-08-30 05:02:38+00:00,SGC2026rauaxm,26.000000,1.472700,0.960000,6.400000,10.535891,10.535891,7.0,7.0,...,earthquake,SGC,"San Agustín - Huila, Colombia",2.100167,-76.529333,MLr_2,Hypo71,RSNC,None,SSWA: Possible duplicate event of SGC2026rauaxl
49,2026-08-30 05:02:41+00:00,SGC2026rauaxl,21.914621,2.449696,1.095312,6.726189,3.634635,4.916613,27.0,18.0,...,earthquake,SGC,"El Tambo - Cauca, Colombia",2.430138,-76.888878,MLr_1,NonLinLoc,Poveda_et_al_2018,None,SSWA: Possible duplicate event of SGC2026rauaxm
50,2026-08-30 05:29:21+00:00,OVSPOP_2833846,10.000000,2.000000,0.070000,NaN,NaN,NaN,22.0,22.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.395667,-76.331333,MLr,,,DESTACADO,Incorrect magnitude type for zone2
51,2026-08-30 18:48:37+00:00,OVSP4910444,14.121221,2.200000,0.070000,NaN,NaN,NaN,13.0,13.0,...,earthquake,OVSP,Área de Influencia del Volcán Galeras,1.290207,-77.415121,MLr,,,,Incorrect magnitude type for zone2
52,2026-08-31 02:43:54+00:00,OVSPOP_2834637,10.000000,2.500000,0.060000,NaN,NaN,NaN,18.0,18.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia",2.398333,-76.334667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
53,2026-08-31 08:21:44+00:00,OVSPOP_2834831,9.200000,3.200000,0.070000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Área En Litigio Limites (Puracé - Cauca, Colombia",2.385330,-76.336660,MLr,,,DESTACADO,Incorrect magnitude type for zone2
54,2026-09-04 19:29:56+00:00,OVSPOP2836980,10.860000,2.300000,0.070000,NaN,NaN,NaN,19.0,19.0,...,volcanic eruption,OVSPOP,"Inzá - Cauca, Colombia - Área de Influencia de...",2.403500,-76.319667,MLr,,,DESTACADO,Incorrect magnitude type for zone2
55,2026-09-04 20:24:21+00:00,OVSP4912495,8.000000,2.200000,0.050000,NaN,NaN,NaN,11.0,11.0,...,earthquake,OVSP,"Pasto - Nariño, Colombia - Área de Influencia ...",1.280000,-77.320000,MLr,,,None,Incorrect magnitude type for zone2
56,2026-09-05 18:46:32+00:00,SGC2026rmvsdy,8.700000,3.100000,0.080000,NaN,NaN,NaN,20.0,20.0,...,volcanic eruption,OVSPOP,"Totoró - Cauca, Colombia - Área de Influencia ...",2.400000,-76.300000,MLr,,,DESTACADO,Incorrect magnitude type for zone2